networks:
    default:
        name: ${EXTERNAL_NET}
        external: true

services:
    web:
        image: nginx:stable-alpine
        container_name: ${APP}
        environment:
            - VIRTUAL_HOST=${HTTP_WEB_URL}
        ports:
            - ${HTTP_WEB_PORT}:80
        restart: on-failure
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app
        depends_on:
            - php-app

    php-app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
                USER: ${USER}
                USER_NAME: ${USER_NAME}
                USER_EMAIL: ${USER_EMAIL}
                USER_ID: ${USER_ID}
        container_name: php-${APP}
        environment:
            - XDEBUG_CLIENT_PORT=${XDEBUG_CLIENT_PORT}
            - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST}
            - XDEBUG_START_WITH_REQUEST=${XDEBUG_START_WITH_REQUEST}
        restart: on-failure
        volumes:
            - .:/var/www/app
